### ISSUE TITLE
`TypeError: connection.close is not a function` in Docker and CLI project setup

### ISSUE THREAD

**Issue by ribeirojose** [ForestAdmin/toolbelt#208]
When running the create project command, it errors out using the regular npm package:

```forest projects:create "sample-proj" --databaseConnectionURL "mongodb://localhost:27017/db-name" --applicationHost "localhost" --applicationPort "3310"  && cd "sample-proj" && npm install -s```

or using Docker:

```docker run --rm --init -it -v `pwd`:/usr/src/app -v ~/.forest.d:/usr/src/cli/.forest.d -e TOKEN_PATH="/usr/src/cli" forestadmin/toolbelt projects:create "sample-proj" --databaseConnectionURL "mongodb://host.docker.internal:27017/sample-proj" --applicationHost "localhost" --applicationPort "3310"```.

Both error out with:

```
√ Connecting to your database
√ Analyzing the database
× Disconnecting from your database
× Cannot generate your project.,An unexpected error occurred. Please reach out for help in our Developers community (https://community.forestadmin.com/) or create a Github issue with following error:
TypeError: connection.close is not a function
```

**Comment by slimee** [comment]
Hi,

You can use this command instead:

`npm install -g lumber-cli@latest -s`

`lumber generate "sample-proj" --connection-url "mongodb://localhost:27017/db-name" --ssl "false" --application-host "localhost" --application-port "3310"`

Regards

**Comment by ribeirojose** [comment]
hey @slimee, thanks for the workaround! I was able to generate a project using lumber before, but I assumed we would want to run the `toolbelt`, so I assumed we'd want to use `forest-cli` (which btw is mentioned in the new onboarding flow in https://www.forestadmin.com/ btw). Does that make sense?

**Comment by arnaudbesnier** [comment]
Hey @ribeirojose,

Sorry to read that you have issues with the new onboarding / toolbelt commands.
Indeed it is the new way to go, and the team is already investigating on the issue you raised to fix it.

In the meantime, as a workaround, as @slimee suggested you can replace `forest project:create` by `lumber generate`.

We'll let you know as soon as the fix is released.
Thanks for your patience.

**Comment by arnaudbesnier** [comment]
@ribeirojose 
The toolbelt [v2.2.3](https://github.com/ForestAdmin/toolbelt/blob/master/CHANGELOG.md#223-2021-07-23) is supposed to fix this issue.

Can you confirm it on your end?
Thanks for your help.

**Comment by ribeirojose** [comment]
Amazing @arnaudbesnier . Seems to be working now, thanks!
